[package]
name = "ganddns"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
duration-string = "0.4"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
ureq = { version = "3", features = ["json"] }
